# Generated by Django 6.0.3 on 2026-03-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=20)),
                ('driver', models.CharField(max_length=30)),
                ('pickuplocation', models.TextField()),
                ('dropofflocation', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('createdat', models.DateTimeField(auto_now=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
